### ISSUE TITLE
[Bug?] Scroll mode doesn't fit images into screen on android

### ISSUE THREAD

**Issue by EnergoStalin** [hymbz/ComicReadScript#105]
I've seen #83 where you said android support not targeted. But for now it works pretty well except image doesn't fit into screen in scroll mode as I can see.

Also I agree with point stated in #83 what android ecosystem lack translation options. So I hope supporting android maybe still worth it.

https://github.com/hymbz/ComicReadScript/assets/49844515/166e9528-a84f-4b3e-bb42-38a8876aaada

For desktop version it's larger but still not fit screen.

https://github.com/hymbz/ComicReadScript/assets/49844515/9582d728-4242-4974-8686-2754bfb14196

Browser: Yandex android
Extension: Tampermonkey
Version: latest

Edit: Also noticed clickable areas broken but I can live with that

**Comment by hymbz** [comment]
Has been updated and fixed.

Clicking in the scroll mode and not getting any response is not a bug, it's actually a feature. After all, it's called "scroll" mode. In scrolling mode, the bug is that the clickable area for displaying the next/previous episode is not shown.

Furthermore, as long as it is not a very difficult requirement to implement, I am still willing to support Android. However, currently PWA cannot directly select folders on Android, only individual files can be selected one by one. Therefore, it is not suitable for translating "local" comics.

---

已更新修复。

滚动模式下点击区域没有生效不是 bug 是功能，毕竟是“滚动”模式嘛。会在滚动模式下显示上/下一话的点击区域才是 bug。

另外，只要不是非常难实现的需求，我还是很愿意支持安卓的。只不过 PWA 目前在安卓上没办法直接选择文件夹，只能一个文件一个文件的选择，所以不适合用来翻译“本地”漫画。

**Comment by EnergoStalin** [comment]
Great job! Thanks again. Confirm as working now
